//
//  PariwisataTSManager.swift
//  IniPariwisata
//
//  Created by IndratS on 13/08/20.
//  Copyright © 2020 IndratSaputra. All rights reserved.
//

import Foundation

struct PariwisataTSManager {
    
    let pariwisataSitesList = [
        PariwisataTouristSites(id: 1, nameSites: "Kota Tua Jakarta", location: "Jl. Taman Fatahillah No.1, RT.7/RW.7, Kota Tua, Pinangsia, Tamansari, Jakarta Barat, Jakarta", openingHours: "24 jam", entranceTicket: "-", description: "Kota Tua Jakarta, juga dikenal dengan sebutan Batavia Lama (Oud Batavia), adalah sebuah wilayah kecil di Jakarta, Indonesia. Wilayah khusus ini memiliki luas 1,3 kilometer persegi melintasi Jakarta Utara dan Jakarta Barat (Pinangsia, Taman Sari dan Roa Malaka). Dijuluki Permata Asia dan Ratu dari Timur pada abad ke-16 oleh pelayar Eropa, Jakarta Lama dianggap sebagai pusat perdagangan untuk benua Asia karena lokasinya yang strategis dan sumber daya melimpah."),
        
        PariwisataTouristSites(id: 1, nameSites: "Taman Mini Indonesia Indah", location: "Ceger, Cipayung, Jakarta Timur, DKI Jakarta", openingHours: "07.00 – 22.00.", entranceTicket: "Rp10.000,- (hanya untuk masuk kawasan)", description: "Taman Mini Indonesia Indah (TMII) merupakan suatu kawasan taman wisata bertema budaya Indonesia di Jakarta Timur. Area seluas kurang lebih 150 hektare[1] atau 1,5 kilometer persegi ini terletak pada koordinat 6°18′6.8″LS,106°53′47.2″BT. Taman ini merupakan rangkuman kebudayaan bangsa Indonesia, yang mencakup berbagai aspek kehidupan sehari-hari masyarakat 26 provinsi Indonesia (pada tahun 1975) yang ditampilkan dalam anjungan daerah berarsitektur tradisional, serta menampilkan aneka busana, tarian, dan tradisi daerah"),
        
        PariwisataTouristSites(id: 1, nameSites: "Museum MACAN", location: "Wisma Akr, Jl. Panjang No.5, RT.11/RW.10, Kebon Jeruk, Jakarta Barat", openingHours: "10.00-19.00 WIB (Selasa – Minggu)", entranceTicket: "Rp 50.000,- (dewasa), Rp 40.000,- (lansia dan pelajar), Rp 30.000,- (anak-anak)", description: "Saat mendengar namanya, mungkin Anda akan salah mengira, karena tempat wisata di Jakarta yang sedang hits ini justru menyimpan beragam karya seni yang memukau. Disingkat dari Museum of Modern and Contemporary Art in Nusantara, Museum MACAN ini merupakan destinasi yang cocok untuk pengagum karya seni baik modern maupun kontemporer."),
        
        PariwisataTouristSites(id: 1, nameSites: "Taman Impian Jaya Ancol", location: "Jalan Lodan Timur No.7, RW.10, Kota Tua, Ancol, Pademangan, Kota Jakarta Utara, DKI Jakarta", openingHours: "24 Jam", entranceTicket: "Rp 25,000", description: "Tempat wisata di Jakarta selanjutnya yang juga cukup populer tak hanya bagi warga Jakarta tetapi para pelancong luar kota ialah Taman Impian Jaya Ancol. Destinasi wisata ini merupakan sebuah kawasan wisata terpadu yang dilengkapi dengan ragam fasilitas bertaraf internasional dengan luas area hingga 552 hektar. Termasuk di dalamnya terdapat taman hiburan, wisata pantai, wisata kulibner, lapangan golf, cottages hingga hotel berbintang."),
        
        PariwisataTouristSites(id: 1, nameSites: "Tugu Monumen Nasional", location: "Gambir, Jakarta Pusat, DKI Jakarta", openingHours: "07.00-00.00 (setiap hari)", entranceTicket: "Rp 10.000 (anak-anak) , Rp 20.000 (dewasa)", description: "Menjelajahi kota Jakarta rasanya belum lengkap kalau tak mampir ke Monas atau Tugu Monumen Nasional. Destinasi yang dibangun di atas tanah seluas 80 hektar ini merupakan sebuah bangunan monumental yang dibangun untuk memperingati dan mengenang jasa para pahlawan kemerdekaan. bentuk monumen bersejarah ini pun memiliki makna yang mendalam."),
        
        PariwisataTouristSites(id: 1, nameSites: "Planetarium Jakarta", location: "Jl. Cikini Raya No.73, Cikini, Menteng, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta", openingHours: "08.00-15.00 (Selasa-Minggu)", entranceTicket: "Rp 12.000 (dewasa), Rp 7.000 (anak-anak)", description: "Belajar mengenal system tata surya, seperti apa planet dan benda-benda luar angkasa lainnya menjadi satu hal yang menarik. Dan Anda bisa mendapatkannya dengan cukup detail dengan kemasan yang atraktif di Planetarium Jakarta. Tempat wisata di Jakarta yang satu ini menjadi satu dari sekian banyak destinasi  yang wajib dikunjungi di Jakarta. Sebab tak hanya memberikan hiburan tetapi juga edukasi pada setiap pengunjungnya, hingga tak heran tempat ini kerap jadi langganan wisata edukasi untuk pelajar."),
        
        PariwisataTouristSites(id: 1, nameSites: "Taman Wisata Alam Mangrove, Angke Kapuk", location: "Jalan Garden House, Kamal Muara, Penjaringan, Kota Jakarta Utara, DKI Jakarta", openingHours: "07.00-18.00 (Senin-Minggu)", entranceTicket: "Rp 25.000 (wisatawan lokal), Rp 250.000 (wisatawan mancanegara)", description: "Jika Anda merasa penat dengan keadaan kota Jakarta yang super sibuk dan hectic, coba menepi sejenak di hutan mangrove yang ada di pesisir utara Jakarta. Tepatnya di Taman Wisata Alam Mangrove Angke Kapuk yang berada di kawasan Penjaringan-Jakarta Utara. Tempat wisata di Jakarta ini punya banya spot menarik untuk dikunjungi. Mulai dari jembatan gantung yang berada di tengah hutan bakau yang cocok untuk spot foto. Lalu jembatan pantau yang bisa digunakan untuk mengamati keindahan di sekeliling hutan bakau, termasuk burung-burung hingga gedung-gedung tingga yang ada di kawasan Pantai Indah Kapuk. Di tempat ini juga terdapat wisata air dan bermain anak hingga pondok kemah jika berniat menginap di kawasan tersebut."),
        
        PariwisataTouristSites(id: 1, nameSites: "Waterboom PIK", location: "Jl. Pantai Indah Barat, Kamal Muara, Penjaringan, Kota Jakarta Utara, DKI Jakarta", openingHours: "10.00-21.00 (Senin-Jum’at) dan 08.00-21.00 (Sabtu-Minggu)", entranceTicket: "Rp 120.000 (anak-anak), Rp 220.000 (dewasa)", description: "Tempat wisata di Jakarta yang juga cukup populer dan banyak diminiati untuk mengisi waktu libur ialah Waterboom yang berada di kawasan Pantai Indah Kapuk. Destinasi yang mengusung tema  ”urban cool” ini punya banyak wahana seru yang menarik. Seperti wahana speed slide, aquatube, twiztler, hair pin dan tentunya banyak lagi wahana seru lainnya."),
        
        PariwisataTouristSites(id: 2, nameSites: "Stone Garden – Padalarang", location: "Citatah, Padalarang, Gunung Masigit, Cipatat, Bandung Barat", openingHours: "pukul 06.00 WIB sampai pukul 17.00 WIB", entranceTicket: "Rp3.000 - Rp6.000", description: "Stone Garden Padalarang merupakan salah satu objek wisata yang berada di Bandung dengan pemandangan yang begitu menarik dengan ketinggian yang memberikan rasa puas. Harga tiket Stone Garden pun tidak begitu mahal. Selain untuk tempat wisata tempat ini juga digunakan untuk belajar sejarah. Konon kabarnya sejarah terbangunnya tempat ini yaitu adanya sebuah laut yang dangkal yang berubah menjadi pegunungan setelah berjuta tahun lamaya."),
        
        PariwisataTouristSites(id: 2, nameSites: "Green Canyon – Pangandaran", location: "Desa Kertayasa, Kecamatan Cijulang, Kabupaten Ciamis", openingHours: "pukul 07.00 sampai dengan 17.00 WIB", entranceTicket: "Rp. 150.000 – 250.000", description: "Green Canyon atau lebih dikenal sebagai Cukang Taneuh oleh warga sekitar, berlokasi di Desa Kertayasa, Kecamatan Cijulang, Kabupaten Ciamis. Kurang lebih 31 km dari Kota Pangandaran. Asal muasal nama Green Canyon sendiri adalah dari seorang turis Perancis yang datang pada tahun 1993. Hal ini dikarenakan airnya yang jernih kehijauan dari sungai dan lumut hijau berlimpah di sisi tebing yang membuatnya populer dengan nama Green Canyon"),

        PariwisataTouristSites(id: 2, nameSites: "Curug Cikaso – Sukabumi", location: "Desa Ciniti,Cibitung,Sukabumi,Jawa Barat,Indonesia,43172.", openingHours: "08.00 – 18.00 WIB", entranceTicket: "Rp3.000", description: "Curug Cikaso merupakan salah satu air terjun terindah yang terdapat di Sukabumi Jawa Barat. Suasananya sejuk dengan air jernih hijau kebiru-biruan, dan dikelilingi pepohonan yang rimbun. Pesona keindahannya sangat menawan, bahkan banyak wisatawan yang mengatakan keindahannya mirip dengan lukisan."),
        
        PariwisataTouristSites(id: 2, nameSites: "Bukit Panembongan – Kuningan", location: "Desa Tembong, Kecamatan Garawangi, Kadatuan, Kabupaten Kuningan, Jawa Barat", openingHours: "-", entranceTicket: "Rp7.000 per orang,", description: "Layaknya wisata alam pada umumnya, pesona utama yang ditawarkan Bukit Panembongan memang tidak jauh-jauh dari pemandangan yang elok, hijau, sekaligus menyejukkan. Hamparan kehijauan yang disajikan khas puncak bukit membuat objek wisata ini menjadi salah satu destinasi pilihan keluarga, dan terutama untuk pasangan.Ketika Anda sampai di Bukit Panembongan, Anda akan dimanjakan dengan panorama pepohonan hijau yang berjajar rapi, seakan menyapa Anda. Udara dingin, karena letaknya di ketinggian, yang merasuk akan membawa ketenangan. Sesekali, suara burung berkicau terdengar, membuat Anda merasa di alam yang tenang dan tenteram. Selain panorama hijau yang menyegarkan, pengunjung juga akan disuguhi pemandangan deretan rumah di bawah bukit."),
        
        PariwisataTouristSites(id: 2, nameSites: "Kampung Karuhun – Sumedang", location: "Jl. Pagarbetis, Citengah,Sumedang Selatan,Sumedang,Jawa Barat,Indonesia,45311", openingHours: "08.00 - 16.00 WIB", entranceTicket: "Rp15.000 - Rp25.000 ", description: "Liburan di Sumedang, jangan hanya mencicipi tahunya yang terkenal lezat itu. Dikenal dengan keindahan alamnya sejak dulu, Sumedang kini memiliki sebuah taman hiburan dengan konsep alam. Objek wisata yang dinamai Kampung Karuhun itu tidak berada di tengah keramaian kota, melainkan di daerah dataran tinggi yang sejuk. Taman ini menawarkan beragam wahana modern yang dipadukan dengan suasana alami pegunungan dan budaya kearifan lokal. Perpaduan tersebut menjadikannya sebagai salah satu destinasi wisata yang sayang jika dilewatkan."),
        
        PariwisataTouristSites(id: 3, nameSites: "Masjid Raya Baiturrahman", location: "Banda Aceh, Aceh, Indonesia", openingHours: "-", entranceTicket: "-", description: "Masjid Raya Baiturrahman pertama kali dibangun di era Kesultanan Aceh. Bagian atap masjid ini dibuat sesuai dengan ciri khas masjid-masjid di Indonesia pada masa itu, atap limas bersusun empat. Terdapat dua versi sejarah mengenai riwayat pembangunan masjid ini. Sebagian sumber menyebutkan masjid ini didirikan pada 1292 M oleh Sultan Alauddin Johan Mahmudsyah. Sementara, sumber yang lain menyebutkan masjid ini didirikan oleh Sultan Iskandar Muda pada 1612 M. Dalam perjalanannya, masjid ini pernah dibumihanguskan oleh Belanda saat serangan ke Koetaradja (Banda Aceh) pada 10 April 1873. Runtuhnya bangunan masjid memicu meletusnya perlawanan masyarakat Aceh. Mereka berjuang mempertahankan masjid hingga darah penghabisan. Pada pertempuran tersebut, pihak Belanda kehilangan seorang panglima mereka, Major General Johan Harmen Rudolf Köhler pada 14 April 1873."),
        
        PariwisataTouristSites(id: 3, nameSites: "Air Terjun Blang Kolam", location: "Desa Sidomulyo, Kecamatan Kuta Makmur. Kabupaten Aceh Utara, Propinsi Nanggro Aceh Darussalam.", openingHours: "-", entranceTicket: "-", description: "Aceh merupakan provinsi ujung barat indonesia yang kaya akan potensi wisata Alamnya, mulai wisata pantai, wisata danau, wisata pulau, wisata kuliner dan masih banyak lagi yang bisa Anda temui di Aceh. Salah satu surga tersembunyi di Aceh yang layak Anda jadikan destinasi tujuan wisata adalah Air Tejun Blang Kolam. Air Tejun Blang Kolam cukup tinggi, memiliki ketinggian sekitar 75 meter. Air terjun yang indah ini, tampak asri dan alami karena di sekelilingnya di bawah rimbunnya pepohonan dan memiliki suasana hutan cukup lebat. Belum lagi ketika Anda saat perjalanan menuju air terjun ini, Anda akan di suguhi oleh pemandangan dan suasana perdesaan yang menyejukkan hati dan mata saat memandangnya"),
        
        PariwisataTouristSites(id: 3, nameSites: "Air Terjun Suhom", location: "Tunong Krueng Kala, Lhoong, Kabupaten Aceh Besar, Aceh 23371", openingHours: "-", entranceTicket: "Rp 5.000 per orang", description: "PEPOHONAN rimbun nan hijau, udara segar, dan bunyi gemuruh air jatuh dari sela bebatuan di perbukitan menuju telaga biru menjadi kombinasi yang memberikan efek relaksasi ketika berada di kawasan Air Terjun Suhom, Kecamatan Lhoong, Kabupaten Aceh Besar, Provinsi Aceh. Kawasan ini menjadi alternatif wisata bahari yang sudah umum di ”Bumi Serambi Mekkah”. Air Terjun Suhom berada di tengah kawasan hutan Lhoong. Jaraknya sekitar 75 kilometer dari Banda Aceh melalui jalur Pantai Barat Aceh. Pengunjung harus menggunakan kendaraan pribadi atau sewa karena belum ada kendaraan umum untuk menuju ke sana."),
        
        PariwisataTouristSites(id: 4, nameSites: "Istana Maimun", location: "Jalan Brigadir Jenderal Katamso, Aur, Medan Maimun, Medan.", openingHours: "-", entranceTicket: "-", description: "Sejarah Istana Maimun kembali ke masa kesultanan Deli. Istana yang merupakan peninggalan Kesultanan Deli ini telah berusia ratusan tahun dan masih ada hingga sekarang. Letak istana ini di kota Medan yang merupakan ibu kota Provinsi Sumatera Utara. Keberadaan istana ini menjadi ikon wisata untuk kota Medan juga destinasi wisata favorit.Adapun sultan Deli yang membangun Istana Maimun bernama Sultan Makmun Al-Rasyid Perkasa Alamsyah. Istana ini mulai dibangun pada tanggal 26 Agustus 1888 kemudian selesai di tahun 18 Mei 1891. Kemegahan Istana Maimun yang menjadi saksi sejarah Kesultanan Deli yang masih bisa dinikmati oleh para wisatawan hingga sekarang."),
        
        PariwisataTouristSites(id: 4, nameSites: "Air Terjun Sipiso-piso", location: "Desa Tongging, Kec. Merek, Kab. Karo, Sumatra Utara.", openingHours: "-", entranceTicket: "-", description: "Air Terjun Sipiso-piso merupakan salah satu tempat wisata di Pulau Sumatera. Berada di Kabupaten Karo, Sumatera Utara, yang tidak begitu jauh dari pemukiman penduduk Desa Tongging. Air terjun ini berada di perbukitan dengan ketinggian sekitar 800 mdpl dan dikelilingi oleh hutan pinus. Pengelolaan wisata alam air terjun ini dipegang oleh Pemda Kabupaten Karo. Dengan memiliki ketinggian sekitar 120 meter, Air Terjun Sipiso-piso merupakan salah satu air terjun tertinggi di Indonesia. Dengan adanya air terjun ini, Kabupaten Karo menjadi salah satu tempat wisata yang paling diminati oleh para wisatawan domestik dan mancanegara."),
        
        PariwisataTouristSites(id: 4, nameSites: "Masjid Raya Medan", location: "Jalan Sisingamangaraja, Medan, Sumatera Utara.", openingHours: "-", entranceTicket: "-", description: "Masjid Raya Al-Mashun atau biasa dikenal Masjid Raya Medan merupakan salah satu peninggalan seorang Sultan Deli di Sumatera Utara yang bernama Sultan Mamoen Al Rasyid Perkasa Alam (1873-1924) yang sangat monumental dan memilki nilai sejarah yang sangat tinggi. Masjid Raya Al-Mashun terletak di Jalan Sisingamangaraja, Medan, Sumatera Utara. Luas Bangunan Masjid sekitar 5000 m2 dan dibangun diatas lahan seluas 18.000 m2 . Pembangunan masjid ini memakan waktu selama 3 tahun yaitu dari tanggal 21 Agustus 1906 sampai 19 September 1909. Masjid Raya ini telah berumur lebih dari 1 abad dan termasuk salah satu bangunan tertua di Kota Medan. Masjid ini sampai sekarang masih digunakan oleh umat Muslim untuk beribadah dan berdoa setiap harinya.Sebagian dari bahan bangunan untuk mendekorasi masjid ini dibuat di negara Italia. Masjid Agung ini adalah masjid yang paling indah dan Masjid terbesar di Sumatera Utara. Masjid ini begitu megah serta mengagumkan dan dikagumi orang lantaran memiliki bentuk tidak sama dengan masjid biasanya."),
        
        PariwisataTouristSites(id: 5, nameSites: "Pantai Carolina", location: "terletak di sebelah Selatan Kota Padang, Provinsi Sumatera Barat. ", openingHours: "-", entranceTicket: "Rp.5000 per orang", description: "Pantai Caroline memiliki kharisma tersendiri. Pasir putih di tepi pantai Padang ini semakin lengkap dengan pepohonan hijau yang berbaris dipinggirannya. Mayoritas pepohonan tersebut adalah pohon kelapa yang landai. Jika Anda berkunjung pada saat cuaca cerah, riak ombak akan memanggil-manggil jiwa petualangan Anda untuk merasakan riuhnya air laut. Pantai di Sumatera Barat ini juga merupakan surga bagi Anda yang gemar surving. Ombaknya sangat menantang untuk ditaklukkan. Tidak hanya itu saja, memancing atau sekedar bermain sepak bola bersama teman-teman Anda juga akan menjadi aktivitas menyenangkan, yang dapat Anda lakukan di Pantai Caroline."),
        
        PariwisataTouristSites(id: 5, nameSites: "Lubuak Rantiang", location: "Sungai Angah, Bangek, Balai Gadang, Koto Tangan, Kota Padang.", openingHours: "-", entranceTicket: "Rp 5.000/orang.", description: "Air Terjun Lubuak Rantiang Kota Padang – Lubuak Rantiang menjadi obyek wisata yang mempunyai pesona alam yang sangatlah memikat. Banyak aktifitas yang dapat dilakukan selama berada di air terjun. Keindahan air terjun ini pun juga sering kali disebut sebagai air terjun Ngalauan. Air terjun yang berada di kota Padang ini mampu menarik perhatian banyak para wisatawan. Melalui panorama yang cukup menggoda bagi para wisatawannya inilah yang mendatangkan banyak wisatawan untuk berkunjung. Melalui pemandangan yang sangat menggoda tersebut, banyak orang yang mencari tahu mengenai lokasi air terjun, harga tiket masuk, aktifitas yang dapat dilakukan di sana, keunikan dari air terjun maupun persiapan yang harus disiapkan sebelum berangkat ke air terjun. Ada baiknya jika Anda mengetahui informasi tersebut dengan membaca ulasan yang ada di bawah ini."),
        
        PariwisataTouristSites(id: 5, nameSites: "Jembatan Siti Nurbaya", location: "Kota Padang", openingHours: "-", entranceTicket: "-", description: "Jembatan Sitti Nurbaya adalah jembatan yang membentang sepanjang 156 meter di atas sungai Batang Arau, Kota Padang, Sumatra Barat. Jembatan ini menghubungkan pusat kota dengan Seberang Padang. Mengambil nama dari novel klasik Sitti Nurbaya karya Marah Rusli, jembatan ini adalah akses menuju Gunung Padang, salah satu latar tempat Sitti Nurbaya.[1] Dibangun sejak tahun 1995, pembangunan jembatan menghabiskan biaya Rp19,8 miliar dari anggaran pemerintah daerah dan pemerintah pusat, dibantu oleh Asian Development Bank (ADB) dan Overseas Economic Cooperation Fund (OECF). Penggunaannya diresmikan pada pertengahan tahun 2002, ditandai dengan kehadiran pemeran drama televisi Sitti Nurbaya HIM Damsyik, Novia Kolopaking, dan Gusti Randa.[1]"),
        
        PariwisataTouristSites(id: 6, nameSites: "Kawah Biru", location: "Desa Tanah Merah, Kecamatan Siak Hulu, Kabupaten Kampar", openingHours: "24 jam", entranceTicket: "Gratis", description: "Kawah Biru yang terletak di Desa Tanah Merah ini sebenarnya adalah lokasi bekas galian yang terisi air hujan sehingga membentuk kawah. Warna air biru yang indah pada objek wisata Pekanbaru ini dihasilkan disebabkan oleh galian pasir berwarna putih bening sehingga warna air terlihat jelas berwarna biru."),
        
        PariwisataTouristSites(id: 6, nameSites: "Sungai Kampar", location: "Sungai Kampar, Teluk Meranti, Kabupaten Pelalawan, Riau", openingHours: "24 jam", entranceTicket: "Gratis", description: "Siapa bilang berselancar hanya bisa dilakukan di laut? Di Sungai Kampar, Toppers bisa berselancar karena sungai ini memiliki ombak yang dikenal oleh warga lokal sebagai “Bono”. Toppers akan merasakan kecepatan ombak 40 kilometer per jam di tujuan wisata favorit Pekanbaru ini dan ombak inilah yang akan membawamu naik hingga ke ketinggian 4 sampai 6 meter."),
        
        PariwisataTouristSites(id: 6, nameSites: "Danau Buatan Khayangan", location: "Jl. Khayangan, Rumbai Pesisir, Kota Pekanbaru, Riau", openingHours: "24 jam", entranceTicket: "Gratis", description: "Tak hanya berfungsi sebagai saluran irigasi, Danau Khayangan juga populer sebagai salah satu destinasi wisata di Pekanbaru. Di Danau Khayangan, pengunjung bisa mengelilingi danau dengan menggunakan sampan atau speedboat, dan para pengunjung juga dapat mendaki bukit di sekitar danau."),
        
        PariwisataTouristSites(id: 7, nameSites: "Bintan Mangrove", location: "Pertokoan Pujasera, Sebong Lagoi, Tlk. Sebong, Kabupaten Bintan, Kepulauan Riau", openingHours: "-", entranceTicket: "Rp 380.000", description: "Bintan Mangrove menjadi salah satu destinasi wisata di Indonesia yang sedang naik daun. Tidak hanya keluarga, bahkan kalangan muda - mudi pun dapat kita jumpai senang mengunjungi area ini. Keindahan alam serta kemurnian daerah yang asri dan terjaga dengan baik mungkin menjadi salah satu alasan tempat ini diincar begitu banyak wisatawan. Tempat indah bak surga dunia ini berada di Pulau Bintan, Kepulauan Riau, tepatnya di Sungat Sebong yang membelah kawasan Kampung Lagoi serta Desa Sebong Lagoi. Banyak aktivitas yang bisa dilakukan di Pulau Bintan itu sendiri, seperti bermain golf, menikmati alam, piknik bersama, atau sekadar bercengkrama dengan kerabat dekat Anda."),
        
        PariwisataTouristSites(id: 7, nameSites: "Gedung LAM Bintan", location: "kawasan Relief Antam, Kijang, Bintan Timur.", openingHours: "pukul 08.00 pagi sampai dengan 21.00 malam", entranceTicket: "", description: "edung LAM Bintan memiliki nama lain, yaitu Megat Seri Rama. Gedung ini sebenarnya lebih sering digunakan untuk keperluan pernikahan karena menurut sebagian besar masyarakatnya, bila menggelar resepsi pernikahan di gedung tersebut akan dianggap lebih istimewa. Oleh karena itu, tak heran jika permintaan untuk sewa gedung pernikahan lebih banyak dibandingkan agenda, acara atau pertemuan lain. Nah, berikut ini terdapat beberapa inti yang akan dijelaskan lebih detail mengenai Gedung Megat Seri Rama atau Lembaga Adat Melayu (LAM) Bintan."),
        
        PariwisataTouristSites(id: 7, nameSites: "Kampung Wisata Panglong", location: "Kecamatan Teluk Sebong", openingHours: "-", entranceTicket: "-", description: "Ponglang merupakan kampung yang terletak di pulau Bintan sebelah utara dengan lokasi yang dekat dengan pelabuhan internasional dan wisata hutan mangrove. Kampung yang terletak di Kecamatan Teluk Sebong ini dihuni oleh kurang lebih 70 keluarga yang berprofesi sebagai nelayan. Meskipun dijadikan tempat wisata, kampung wisata ponglang tak memiliki hal istimewa seperti halnya kampung wisata lainnya.Saat memasuki kawasan kampung wisata ponglang, Anda tidak akan disambut dengan tari selamat datang seperti yang dilakukan oleh kampung wisata lainnya didaerah Riau. Anda juga tidak akan menemukan penjual souvenir, jejeran restoran dekat pantai, ataupun pamflet-pamflet penginapan. Karena kampung ini tidak menyediakan fasilitas khusus semacam itu, kampung panglong ini memang sengaja di biarkan layaknya kampung biasa agar tetap terkesan natural."),
        
        PariwisataTouristSites(id: 8, nameSites: "Pulau Penyu", location: "Kecamatan Sadu, Kabupaten Tanjung Jabung Timur, Provinsi Jambi", openingHours: "-", entranceTicket: "-", description: "Menikmati eksotisme pulau tak berpenghuni, dengan hamparan pasirnya yang cantik serta melihat lebih dekat kehidupan penyu dihabitat aslinya menjadi satu hal yang tak akan terlupakan. Hal tersebut bisa Anda dapatkan dengan menjelajahi tempat wisata di pesisir timur Jambi, yakni Pulau Penyu.Pulau kecil ini merupakan salah satu tempat yang disukai para penyu untuk menyimpan telur-telurnya karena dirasa lebih aman sebab tak dihuni oleh manusia. Tak heran memang, karena akses menuju pulau cantik ini belum terakomodir. Sehingga jarang ada orang dating."),
        
        PariwisataTouristSites(id: 8, nameSites: "Bukit Ngarau Merangin", location: "Kecamatan Tabir Ulu, Kabupaten Merangin, Provinsi Jambi", openingHours: "-", entranceTicket: "-", description: "Ingin melihat pemandangan Jambi dari sudut yang berbeda? Maka angan lewatkan kesempatan berkunjung ke tempat wisata di Jambi yang satu ini. Di Merangin ada Bukit Ngarau yang akan menawarkan pesona lanskap Jambi dan kota-kota disekitarnya yang begitu memukau dari ketinggian.Saat berada di puncak bukit, Anda akan disuguhi pemandangan alam yang sungguh aduhai sambil meresapi sejuknya hawa segar di pegunungan. Jangan lupa bawa kamera atau smartphone, karena tempat ini punya spot yang instagramable buat jadi background foto kekinian!"),
        
        PariwisataTouristSites(id: 8, nameSites: "Air terjun Renah Sungai Besar", location: "Renah Sungai Besar, Limbur Lubuk Mengkuang, Kabupaten Bungo, Jambi", openingHours: "-", entranceTicket: "-", description: "Jambi dianugerahi alam yang begitu menakjubkan, tak heran jika kemudian banyak yang tertarik untuk mengeksplorasinya. Salah satunya sebagai kawasan wisata, seperti di Ranah Sungai Besar misalnya yang memiliki air terjun yang memukau dan masih alami.Volume airnya yang deras membuat air terjun ini begitu mempesona ditambah dengan airnya yang sejuk dan dikelilingi panorama alam nan asri membuat siapapun betah berlama-lama di sini untuk menghilangkan stress yang melanda."),
        
        PariwisataTouristSites(id: 9, nameSites: "Benteng Marlborough", location: "Jalan Benteng, Kelurahan Kebun Keling, Kecamatan Teluk Segara, Kota Bengkulu", openingHours: "08.00-18.00 WIB", entranceTicket: "Rp5.000", description: "Benteng peninggalan Inggris ini sempat digunakan untuk kantor, penjara, dan barak. Pada tahun 1977, Depdikbud mengambil alih benteng dan melakukan pemugaran. Bangunan yang desainnya menyerupai bentuk kura-kura ini sangat luas. Menariknya, bagian belakang benteng langsung menghadap ke Samudera Hindia. "),
        
        PariwisataTouristSites(id: 9, nameSites: "Pantai Air Bengkenang", location: "Kelurahan Tanjung Besar, Kecamatan Manna, Kabupaten Bengkulu Selatan", openingHours: "24 jam ", entranceTicket: "Rp7.000", description: "Meski jalan menuju pantai ini cukup licin dan sulit dilalui, semua perjuangan kamu bakal terbayar lunas saat melihat keindahan pantai dengan beragam spot  menarik. Kamu juga bisa menikmati hasil laut yang segar dan nikmat. "),
        
        PariwisataTouristSites(id: 9, nameSites: "Pantai Sungai Suci", location: "Jalan Pesisir Pantai Panjang, Kecamatan Pondok Kelapa, Kabupaten Bengkulu Tengah", openingHours: "24 jam", entranceTicket: "Rp5.000", description: "Saat mengunjungi pantai ini, kamu akan langsung disuguhkan pulau kecil di tengah laut. Kamu bisa menyeberang melalui jembatan gantung yang cukup menguji adrenalin. Tenang, jembatan tersebut terbuat dari tali tambang yang kuat dengan alas papan kayu tebal. "),
        
        PariwisataTouristSites(id: 10, nameSites: "Gunung Dempo", location: "Sumatera Selatan", openingHours: "-", entranceTicket: "-", description: "Gunung Dempo terletak di Kota Pagaralam dengan jarak tempuh darat sekitar 7 jam dari Palembang, ibu kota Provinsi Sumatera Selatan. Sesuai dengan namanya, Kota Pagaralam dikelilingi oleh pegunungan Bukit Barisan dan yang tertinggi adalah Gunung Dempo.Jika di Jawa Barat ada Puncak Bogor, Kota Pagaralam sering disebut juga sebagai puncaknya Sumatera Selatan. Sebab, konturnya daerah pegunungan maka udara sejuk akan menyambut Anda ketika tiba di tempat ini."),
        
        PariwisataTouristSites(id: 10, nameSites: "Bukit Jempol", location: "Sumatera Selatan", openingHours: "-", entranceTicket: "-", description: "Bagian barat Sumatera Selatan dikenal sebagai daerah yang memiliki kontur bergelombang. Tidak  mengherankan jika di wilayah ini banyak ditemukan objek wisata alam eksotis, baik berupa bukit atau pun curug dengan berbagai karakternya yang unik. Lahat misalnya, di kabupaten yang berjarak sekitar 270 km dari ibukota Palembang ini terdapat bukit unik, yang oleh masyarakat lebih dikenal dengan nama Bukit Jempol.Bukit Jempol mempunyai nama peta Bukit Serelo, bukit ini berlokasi di Desa Perangai yang berjarak sekitar 20 km dari pusat Kota Lahat. Jika menggunakan kendaraan darat, ada satu cara untuk bisa mendapatkan pemandangan terbaik Bukit Jempol dari dekat, yaitu dengan memasuki kawasan pertambangan yang ada di perbatasan Lahat dan Muara Enim. Dari kawasan pertambangan ini, pemandangan Bukit Jempol bisa dilihat dengan sempurna.Sesuai dengan namanya, Kota Pagaralam dikelilingi oleh pegunungan Bukit Barisan dan yang tertinggi adalah Gunung Dempo."),
        
        PariwisataTouristSites(id: 10, nameSites: "Danau Ranau", location: "Kabupaten Lampung Barat; Lampung; Indonesia Kabupaten Ogan Komering Ulu Selatan; Sumatra Selatan; Indonesia.", openingHours: "-", entranceTicket: "-", description: "Danau Ranau adalah danau terbesar kedua di Sumatra setelah Danau Toba. Danau ini terletak di perbatasan Kabupaten Lampung Barat Provinsi Lampung dan Kabupaten Ogan Komering Ulu Selatan Provinsi Sumatra Selatan. Danau ini tercipta dari gempa besar dan letusan vulkanik dari gunung berapi yang membuat cekungan besar. Terletak pada posisi koordinat"),
        
        PariwisataTouristSites(id: 11, nameSites: "Pantai Tongaci", location: "Kampung Pasir, Jalan Laut, Kampung Laut, Sungai Liat Kabupaten Bangka", openingHours: "-", entranceTicket: "Mulai dari Rp.8.000", description: "Ratusan tukik jenis Penyu Hijau dan Penyu Sisik berbagai ukuran berenang dalam sebuah kolam. Di sisi lain tampak penyu sedang menetas. Pemandangan seperti itu sudah biasa terjadi di tepi Pantai Tongaci. Tempat konservasi ini didirikan sebagai upaya untuk melindungi penyu dari kepunahan serta memberikan edukasi kepada masyarakat tentang pentingnya menjaga alam. Selain bisa melihat penyu-penyu lucu bercengkrama, sobat tiket tentunya disuguhi pemandangan pantai yang menawan. Payung-payung khas China menyambut sobat tiket saat pertama kali menuju kawasan Pantai Tongaci. Suasana jadul terpancar dengan adanya ornamen unik dan klasik."),
        
        PariwisataTouristSites(id: 11, nameSites: "Pantai Tikus", location: "Parit Padang, Sungai Liat Kabupaten Bangka", openingHours: "-", entranceTicket: "Gratis!", description: "Sebuah Vihara megah bersanding dengan pancaran warna biru dari laut menampilkan pemandangan yang tidak biasa. Nama Pantai Tikus kabarnya karena di sekitar pantai banyak jalan tikus alias jalan setapak yang konon kabarnya digunakan oleh penambang timah gelap untuk membawa hasil tambangnya ke tepian pantai. Selain itu, ada juga yang menyebutkan kalau dahulu di area pantai ini terdapat banyak tikus berkeliaran. Fasilitas yang disediakan oleh pengelola cukup lengkap untuk pantai yang tergolong baru. Olahraga air, voli pantai, flying fox, sampai berkemah bisa sobat tiket.com lakukan di Pantai Tikus. Dengan jarak tempuh sekitar 45 menit dari Kota Pangkalpinang, kamu sudah bisa menikmati keindahan pasir putih dengan sedikit batu granit.Fasilitas yang disediakan oleh pengelola cukup lengkap untuk pantai yang tergolong baru. Olahraga air, voli pantai, flying fox, sampai berkemah bisa sobat tiket.com lakukan di Pantai Tikus. Dengan jarak tempuh sekitar 45 menit dari Kota Pangkalpinang, kamu sudah bisa menikmati keindahan pasir putih dengan sedikit batu granit."),
        
        PariwisataTouristSites(id: 11, nameSites: "Batu Garuda", location: "Sijuk, Kabupaten Belitung", openingHours: "-", entranceTicket: "Gratis!", description: "Puluhan batu granit raksasa tertata cantik membentuk seperti kepala burung garuda. Tak heran jika dijadikan salah satu lokasi syuting film Laskar Pelangi karena keindahannya yang luar biasa. Sobat tiket bisa menempuh perjalanan sekitar 27 kilometer dari Tanjung Pandan untuk mencapai lokasi Batu Garuda. Pantai Tanjung Kelayang yang merupakan lokasi Batu Garuda ditetapkan sebagai Kawasan Ekonomi Khusus pada tanggal 15 Maret 2016 dengan kegiatan utama di bidang pariwisata. Nama Pantai Tanjung Kelayang disematkan pada pantai ini karena terdapat banyak burung kelayang di sekitar pantai. Sobat tiket juga bisa menikmati sensasi mengelilingi pulau sekitar dengan menyewa perahu nelayan."),
        
        PariwisataTouristSites(id: 12, nameSites: "Pantai Pasir Putih", location: "Rangai Tri Tunggal, Katibung, Lampung Selatan, Lampung", openingHours: "24 jam", entranceTicket: "-", description: "Pantai satu ini tengah jadi tujuan wisata di Lampung yang paling hits. Selain pasir putihnya yang terkenal, pantai ini juga menawarkan berbagai panorama indah lainnya yang dapat dinikmati, baik untuk beraktivitas maupun sekedar bersantai."),
        
        PariwisataTouristSites(id: 12, nameSites: "Pantai Tanjung Setia", location: "Desa Tanjung Setia, Krui, Lampung Barat, Lampung", openingHours: "24 jam", entranceTicket: "-", description: "Untuk Toppers yang suka menantang ombak, pantai Tanjung Setia adalah tempat wisata di Lampung yang sangat cocok untuk membuktikan skill berselancar. Selain ombak yang kuat, fasilitas penginapan disini juga sudah tersedia lengkap."),
        
        PariwisataTouristSites(id: 12, nameSites: "Teluk Kiluan", location: "Sukarame, Punduh Pidada, Kabupaten Pesawaran, Lampung", openingHours: "24 jam", entranceTicket: "-", description: "Teluk Kiluan terkenal di kalangan wisatawan karena di sini kamu bisa melihat langsung ikan lumba-lumba. Tidak hanya itu, wisatawan bahkan bisa berenang langsung di laut bersama mereka! Di tempat wisata alam di Lampung ini, Toppers bisa memanfaatkan Kamera Underwater untuk mengambil momen-momen terbaik bersama teman dan keluarga!"),
        
        PariwisataTouristSites(id: 13, nameSites: "Pantai Anyer", location: "Jalan Raya Anyer, Kecamatan Anyer, Kabupaten Serang, Provinsi Baten.", openingHours: "-", entranceTicket: "Rp 5.000", description: "Daftar objek wisata di Banten paling terkenal kami mulai dari pantai Anyer.        Pantai ini berlokasi di Anyer, Kabupaten Serang, Banten. Jaraknya sekitar 45,9 kilometer dari pusat kota Serang dan bisa ditempuh dalam waktu kurang lebih satu jam berkendara melalui Jl. Raya Pantura. Pantai Anyer cukup terkenal di kalangan wisatawan lokal, setiap harinya kawasan pantai ini selalu dipadati oleh puluhan hinga ratusan orang yang datang bersama keluarga ataupun teman-teman sekantor."),
        
        PariwisataTouristSites(id: 13, nameSites: "Gunung Krakatau", location: "Selat Sunda,  Indonesia Geologi", openingHours: "-", entranceTicket: "-", description: "Mendaki gunung menjadi aktivitas yang tiada duanya bagi mereka yang hobi mendaki. Nah bagi kalian yang senang dengan aktivitas ini, kalian bisa mencoba tantangan mendaki gunung Krakatau di Banten. Gunung ini memiliki tinggi sekitar 813 meter dari permukaan laut. Tidak terlalu tinggi memang, tapi daya tariknya selain jalur trekingnya yang menantang, kalian juga bisa mendaki sambil menikmati lanscape selat sunda yang terlihat kebiruan."),
        
        PariwisataTouristSites(id: 13, nameSites: "Pantai Sawarna", location: "Desa Sawarna, yang ada di Kecamatan Bayah, Kabupaten Lebak, Propinsi Banten.", openingHours: "-", entranceTicket: "10 ribu hingga 15 rupiah", description: "Pantai ini berjarak sekitar 169,9 kilometer dari pantai Anyer. Tergolong pantai baru di Banten sehingga keberadaannya masih belum banyak diketahui oleh para wisatawan. Namun akhir-akhir ini, pantai Sawarna mulai mendapat kunjungan stabil setelah banyak wisatawan luar negeri menjadikannya sebagai lokasi berselancar. Gelombang ombaknya cukup besar sehingga sangat bersahabat untuk kegiatan tersebut."),
        
        PariwisataTouristSites(id: 14, nameSites: "Candi Borobudur", location: "Kecamatan Borobudur, Kabupaten Magelang, Provinsi Jawa Tengah.", openingHours: "08.00 - 16.00 WIB", entranceTicket: "Dewasa : Rp 40.000/orang Anak – anak : Rp 20.000/orang Mancanegara : USD 25, Pelajar mancanegara : USD 15", description: "Untuk pertama kali nama Borobudur tertulis dalam buku “Sejarah Pulau Jawa” oleh Sir Thomas Raffles. Nama Borobudur diambil dari kata bara dari bahasa Sanskerta yang mempunyai arti ‘komplek candi’atau biara dan kata ‘budur’ berasal dari kata ‘beduhur’ yang artinya ‘di atas’. Jadi makna dari kata Borobudur adalah Candi yang berada di atas bukit. Candi Borobudur dibangun sekitar tahun 750 masehi oleh kerajaan syailendra yang didirikan oleh Raja Mataram bersama Samaratungga yang pada saat itu menganut agama Buddha. Candi Borobudur dibangun sangat misterius karena pada abad ke 7 manusi belum mengenal perhitungan arsitektur yang tinggi  tetapi Candi Borobudur dibangun dengan perhitungan arsitektur yang canggih. Borobudur adalah candi terbesar di dunia sekaligus salah satu monumen Buddha terbesar di dunia. Candi borobudur ini memiliki 72 stupa yang berbentuk lonceng, stupa yang terbesar terletak pada puncak candi sedangkat yang lainnya mengelilingi stupa sampai ke bawah."),
        
        PariwisataTouristSites(id: 14, nameSites: "Candi Prambanan", location: "Prambanan Temple Jl. Raya Solo - Yogyakarta No.16, Kranggan, Bokoharjo,Prambanan,Sleman,DI Yogyakarta,Indonesia,55571.", openingHours: "08.00 - 16.00 WIB", entranceTicket: "Rp25.000 - Rp75.000 ", description: "Ketika berkunjung ke tempat wisata di Jawa Tengah ini, Anda tidak hanya akan disuguhi dengan jejak sejarah yang eksotis, tapi juga hijaunya pepohonan yang tumbuh di sekitar area candi. Pun karena terletak di perbatasan, candi ini dikelola secara kerja sama antara DIY dan Jawa Tengah. Candi Prambanan yang merupakan komplek candi Hindu terbesar di Indonesia pernah mengalami beberapa kali pemugaran, terutama pasca gempa Jogja pada 2006 silam. Meski begitu, kesan asli candi yang bersejarah tetap tidak hilang dari bangunan ini."),
        
        PariwisataTouristSites(id: 14, nameSites: "Lawang Sewu", location: "Jl. Pemuda, Sekayu,Semarang Tengah,Semarang,Jawa Tengah,Indonesia,50132.", openingHours: "07.00 - 21.00 WIB", entranceTicket: "Rp5.000 - Rp10.000", description: "Pada zaman dulu, Lawang Sewu dipakai sebagai kantor pusat perkeretaapian di wilayah Semarang. Tidak heran kalau berkunjung ke sini, Anda akan melihat banyak miniatur kereta yang dipajang di meja yang dilindungi kaca-kaca. Aura mistis seketika akan menyergap Lawang Sewu pada malam hari. Kalau Anda suka menguji nyali, cobalah datang dan jelajahi bangunan kuno ini ketika matahari sudah terbenam, dijamin bulu kuduk Anda akan merinding. Keindahan dan keklasikan arsitektur bangunannya juga membuat tempat wisata di Jawa Tengah ini sering dijadikan latar fotografi, syuting film, dan semacamnya."),
        
        PariwisataTouristSites(id: 15, nameSites: "Keraton Yogyakarta", location: "Jalan Rotowijayan Blok No. 1, Panembahan,Kraton,Yogyakarta,DI Yogyakarta,Indonesia,55132.", openingHours: "08.30 - 13.00 WIB", entranceTicket: "Rp5.000 - Rp15.000", description: "Keraton Yogyakarta menjadi salah satu ikon wisata bersejarah di Yogyakarta selain Candi Borobudur. Keraton yang merupakan istana kesultanan Ngayogyakarta Hadiningrat ini masih berfungsi sebagai tempat tinggal sultan. kompleks keraton kini sebagian beralih fungsi sebagai museum benda-benda koleksi milik kesultanan. Keraton Yogyakarta masih menjaga warisan budaya seperti kegiatan upacara adat, dan benda-benda kuno lainnya. Nilai-nilai filosofi dan mitologi masih melingkupi kehidupan di Keraton Yogyakarta."),
        
        PariwisataTouristSites(id: 15, nameSites: "Taman Sari Jogja", location: "Jl. Taman Sari No.42, Kadipaten,Kraton,Yogyakarta,DI Yogyakarta,Indonesia,55132.", openingHours: "09.00 - 15.00 WIB", entranceTicket: "Rp5.000 - Rp15.000", description: "Jaman dulu Taman Sari Jogja merupakan tempat rekreasi dan meditasi keluarga kerajaan Yogyakarta. Pesona Istana Taman Sari terletak pada keindahan arsitekturnya yang kuno dan pemandangan yang indah. Istana ini dibangun untuk menghargai jasa para istri Sultan yang telah membantu semasa perang. Istana ini dikelilingi dengan taman bunga yang memberikan wangi semerbak ke sekitarnya."),
        
        PariwisataTouristSites(id: 15, nameSites: "Museum Gunung Merapi", location: "Jl. Kaliurang No.Km, Banteng, Hargobinangun,Pakem,Sleman,DI Yogyakarta,Indonesia,55582.", openingHours: "08.00 - 15.30 WIB", entranceTicket: "Rp5.000 - Rp10.000 ", description: "Salah satu tempat wisata di Kaliurang yang wajib ada kunjungi nih. Museum Gunung Merapi ini diresmikan pada tahun 2009, dan terletak sekitar 5 Km dari Kaliurang.Museum ini merupakan sarana pendidikan dan informasi mengenai kegunungapian dan bencana geologi lainnya. Di tempat ini juga di pamerkan karya seni yang melukiskan dongeng asal muasal Merapi"),
        
        
    ]
    
    
    // fungsi untuk dapetin nomer arraynya
    func getNumberArray(id: Int) -> [Int]{
        var myIndex = [Int]()
        for (key,data) in pariwisataSitesList.enumerated() where data.id == id {
//            if data.id == id {
                myIndex.append(key)
//            }
        }
        return myIndex
    }
    
}

